---
# This playbook will install mysql and create db user and give personal

  - name: Install MariaDB package
    yum:
      name: "{{ item }}"
      state: latest
    loop:
     - mariadb
     - mariadb-server   

  - name: Configure SELinux to start mysql on any port
    seboolean:
      name: mariadb_connect_any
      state: true
      persistent: yes
    when: sestatus.rc != 0 and ansible

  - name: Create Mariadb configuration file
    template:
      src: my.cnf.j2
      dest: /etc/my.cnf
    notify:
    - restart mariadb

  - name: Start Mariadb Service
    service:
      name: mariadb
      state: started
      enabled: yes

  - name: insert iptables rule
    lineinfile:
      dest: /etc/sysconfig/iptables
      state: present
      regexp: "{{ mysql_port }}"
      insertafter: "^:OUTPUT "
      line: "-A INPUT -p tcp  --dport {{ mysql_port }} -j  ACCEPT"
    notify: restart iptables

  - name: Create Application Database
    mysql_db:
      name: "{{ dbname }}"
      state: present

  - name: Create Application DB User
    mysql_user:
      name: "{{ dbuser }}"
      password: "{{ upassword }}"
      priv: "*.*:ALL"
      host: '%'
      state: present
