---
# These tasks install http and the php modules.

- name: Install http and php centos
  yum:
    name: "{{ item }}"
    state: latest
  loop:
   - httpd
   - php
   - git
   - python3-libsemanage
   - python3-libselinux
  when: ansible_os_family == "RedHat"

- name: Install http and php ubuntu
  apt:  
    name: "{{ item }}"
    state: latest
  loop:
   - apache2
   - php
   - git   
  when: ansible_os_family == "Debian"

- name: insert iptables rule for httpd
  lineinfile:
    dest: /etc/sysconfig/iptables
    create: yes
    state: present
    regexp: "{{ httpd_port }}"
    insertafter: "^:OUTPUT "
    line: "-A INPUT -p tcp  --dport {{ httpd_port }} -j  ACCEPT"
  notify: restart iptables

- name: http service state centos
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: http service state ubuntu
  service:
    name: apache2
    state: started
    enabled: yes
  when: ansible_os_family == "Debian"

- name: Configure SELinux to allow httpd to connect to remote database
  seboolean:
    name: httpd_can_network_connect_db
    state: true
    persistent: yes
  when: sestatus.rc != 0
