---
# This playbook contains common plays that will be run on all nodes.

- name: Install ntp ubuntu
  apt:
    name: ntpdate
    state: present
  tags: ntp
  when: ansible_os_family == "Debian"

- name: Install chrony centos
  yum:
    name: chrony
    state: present
  tags: ntp
  when: ansible_os_family == "RedHat"

- name: Configure ntp file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  tags: ntpd
  notify: restart ntpd
  when: ansible_os_family == "Debian"

- name: Start the ntpd service ubuntu
  service:
    name: ntp
    state: started
    enabled: yes
  tags: ntpd
  when: ansible_os_family == "Debian"

- name: Start the crony service centos
  service:
    name: chronyd
    state: started
    enabled: yes
  tags: chronyd
  when: ansible_os_family == "RedHat"

- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false
